name: OSS Governance

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@b15a54460c38f54043fa75f7b08a0e2aa5b94b5b # v4.0.0
        with:
          config-path: .github/labeler.yml
