name: Publish

on:
  release:
    types: [published]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release Publishing
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - run: corepack enable pnpm

      - uses: actions/setup-node@5ef044f9d09786428e6e895be6be17937becee3a
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)){
              return semver
            }
            throw new Error('not semver')
          result-encoding: string

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Version
        run: |
          node ./scripts/version.js --version ${{ steps.version.outputs.result }}
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.ORDZAAR_NPM_BOT }}
