name: Publish

on:
  release:
    types: [published]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    environment: NPM Release Publishing
    steps:
      - uses: actions/checkout@7739b9ba2efcda9dde65ad1e3c2dbe65b41dfba7

      - run: corepack enable pnpm

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - uses: actions/github-script@6f00a0b667f9463337970371ccda9072ee86fb27
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)){
              return semver
            }
            throw new Error('not semver')
          result-encoding: string

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Version
        run: |
          node ./scripts/version.js --version ${{ steps.version.outputs.result }}
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm run publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
